"""Поправлены модели Device, DeviceModel, DeviceType, DeviceManufacturer. Добавлена модель RTObject.

Revision ID: 296a458cdca4
Revises: 37f2c58f6e07
Create Date: 2025-09-18 16:05:56.343888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '296a458cdca4'
down_revision: Union[str, Sequence[str], None] = '37f2c58f6e07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rtobjects',
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address'),
    sa.UniqueConstraint('number')
    )
    op.add_column('devicemanufacturers', sa.Column('name', sa.String(), nullable=False))
    op.add_column('devicemanufacturers', sa.Column('model_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('devicemanufacturers_manufacturer_key'), 'devicemanufacturers', type_='unique')
    op.create_unique_constraint(None, 'devicemanufacturers', ['name'])
    op.create_foreign_key(None, 'devicemanufacturers', 'devicemodels', ['model_id'], ['id'])
    op.drop_column('devicemanufacturers', 'manufacturer')
    op.add_column('devicemodels', sa.Column('manufacturer_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'devicemodels', 'devicemanufacturers', ['manufacturer_id'], ['id'])
    op.add_column('devices', sa.Column('rtobject_id', sa.UUID(), nullable=True))
    op.create_unique_constraint(None, 'devices', ['rtobject_id'])
    op.create_foreign_key(None, 'devices', 'rtobjects', ['rtobject_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.drop_constraint(None, 'devices', type_='unique')
    op.drop_column('devices', 'rtobject_id')
    op.drop_constraint(None, 'devicemodels', type_='foreignkey')
    op.drop_column('devicemodels', 'manufacturer_id')
    op.add_column('devicemanufacturers', sa.Column('manufacturer', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'devicemanufacturers', type_='foreignkey')
    op.drop_constraint(None, 'devicemanufacturers', type_='unique')
    op.create_unique_constraint(op.f('devicemanufacturers_manufacturer_key'), 'devicemanufacturers', ['manufacturer'], postgresql_nulls_not_distinct=False)
    op.drop_column('devicemanufacturers', 'model_id')
    op.drop_column('devicemanufacturers', 'name')
    op.drop_table('rtobjects')
    # ### end Alembic commands ###
