"""Добавлены модели для устройств schemas/device.py models/device.py

Revision ID: 37f2c58f6e07
Revises: e22910bef0e9
Create Date: 2025-09-16 13:59:48.882315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37f2c58f6e07'
down_revision: Union[str, Sequence[str], None] = 'e22910bef0e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devicemanufacturers',
    sa.Column('manufacturer', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('manufacturer')
    )
    op.create_table('devicemodels',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('devicetypes',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('devices',
    sa.Column('inventary_number', sa.String(), nullable=True),
    sa.Column('type_id', sa.UUID(), nullable=False),
    sa.Column('manufacturer_id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['devicemanufacturers.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['devicemodels.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['devicetypes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inventary_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('devices')
    op.drop_table('devicetypes')
    op.drop_table('devicemodels')
    op.drop_table('devicemanufacturers')
    # ### end Alembic commands ###
