"""Изменены модели - Device, поле rt_object uselist=True

Revision ID: 7dad94b4810c
Revises: f66f76999d80
Create Date: 2025-09-24 08:54:50.598589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dad94b4810c'
down_revision: Union[str, Sequence[str], None] = 'f66f76999d80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
