"""Изменены модели - Device  поле rtobjects

Revision ID: 8e7b8260d3f4
Revises: 5005418825ac
Create Date: 2025-09-25 08:58:36.270559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e7b8260d3f4'
down_revision: Union[str, Sequence[str], None] = '5005418825ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
