"""Изменены модели - Device  поле rtobjects

Revision ID: 987f8f0a8dfd
Revises: a3fb644a5522
Create Date: 2025-09-25 09:55:27.984602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '987f8f0a8dfd'
down_revision: Union[str, Sequence[str], None] = 'a3fb644a5522'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
