"""Изменены модели - RTObject поле devices

Revision ID: 9d0f9014edbb
Revises: ae7b21ab8e66
Create Date: 2025-09-24 11:14:06.866554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d0f9014edbb'
down_revision: Union[str, Sequence[str], None] = 'ae7b21ab8e66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
