"""Изменены модели дополнены связи от GPT

Revision ID: 9e53b2f3a235
Revises: a3983a61fee8
Create Date: 2025-09-23 14:08:46.354752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e53b2f3a235'
down_revision: Union[str, Sequence[str], None] = 'a3983a61fee8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
