"""Изменена модель Device

Revision ID: a3983a61fee8
Revises: b7c39b9a4431
Create Date: 2025-09-23 08:03:55.729223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3983a61fee8'
down_revision: Union[str, Sequence[str], None] = 'b7c39b9a4431'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('devices_manufacturer_id_fkey'), 'devices', type_='foreignkey')
    op.drop_constraint(op.f('devices_type_id_fkey'), 'devices', type_='foreignkey')
    op.drop_column('devices', 'manufacturer_id')
    op.drop_column('devices', 'type_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('type_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('devices', sa.Column('manufacturer_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('devices_type_id_fkey'), 'devices', 'devicetypes', ['type_id'], ['id'])
    op.create_foreign_key(op.f('devices_manufacturer_id_fkey'), 'devices', 'devicemanufacturers', ['manufacturer_id'], ['id'])
    # ### end Alembic commands ###
