"""Изменены модели - Device  поле rtobjects

Revision ID: a3fb644a5522
Revises: 8e7b8260d3f4
Create Date: 2025-09-25 09:48:54.794115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3fb644a5522'
down_revision: Union[str, Sequence[str], None] = '8e7b8260d3f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
