"""Изменены модели - RTObject поле devices

Revision ID: ae7b21ab8e66
Revises: b1f5928240fe
Create Date: 2025-09-24 10:04:34.709045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae7b21ab8e66'
down_revision: Union[str, Sequence[str], None] = 'b1f5928240fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
