"""Изменены модели - RTObject поле devices теперь list

Revision ID: b1f5928240fe
Revises: 7dad94b4810c
Create Date: 2025-09-24 09:16:14.239522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1f5928240fe'
down_revision: Union[str, Sequence[str], None] = '7dad94b4810c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
