"""Изменены модели - удалены поля models из DeviceType и DeviceManufacturer

Revision ID: f4764b354764
Revises: 9e53b2f3a235
Create Date: 2025-09-23 14:25:47.850041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4764b354764'
down_revision: Union[str, Sequence[str], None] = '9e53b2f3a235'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
