"""Изменены модели - Device, поле rt+object не уникольно

Revision ID: f66f76999d80
Revises: f4764b354764
Create Date: 2025-09-24 08:25:40.527249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f66f76999d80'
down_revision: Union[str, Sequence[str], None] = 'f4764b354764'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('devices_rtobject_id_key'), 'devices', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('devices_rtobject_id_key'), 'devices', ['rtobject_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
